sudo: required
language: generic
services: docker
script:
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic resume.tex"
deploy:
  provider: releases
  api_key:
    secure: z7jB1wkWp1ZbIkGUuY4mrOSmq5xpbYAJH7KfIdqYYZ3ig+WqsjqwhpVkCImlPiVd7QY7CdFC+7RWtjoWIm64T+2yzvvT0opy4S/smBieQ6QsnV8IF4UOtD8G6zwieRdThFW356S8juelHfny6ZcEC4aLSykFEiJ7jVVF3lc94uh/0EyNGpSZtVfDhloVPW1heYPw7qz2Ei+Swg7y7Xoc6F9KeowHjvuU2V0e7r8JY+Wmr20iX+WZRZnfPLCYA0Vp3vZsK4uSV7DKKHJ0iuCZgTtNG3hGr5usinInI64h3u1E19jz0ICztg7hf7Err1TOKLDVW59R7QojV1DNcl+yOGgzfUxO2ix9tIghVmvE7fh9vYj+Lc5V/IMG04TqHTFto3XvtL7z8LxqoLis55/jzhMe9MZIRZZbEi8Yt74wEVxtgsYCfaf2WOSZdr7qSHHoqJWrOyrXSmPRcvK9WwG0IvnobZGPmb//F5ZxNu0Y5BfomZGcLHJsVDngE21ESFIbbBzdMrwa8kqzyXHsUHWw/CL41qjVgokNISk6WCK7x1XFFMhPt9oMggrZA7y+f4eRFHvmbE4arcxsFG2B+1N6dkm2Umilci+RbYpHXmu2EsE7W/fs9lTls22HbVrWv/d0b+FzC5Ud002mrb5Lw6/6+0lyqJaonvxD3LmFj6X7nVc=
  file: ./resume.pdf
  on:
    repo: DKXXXL/resume
    tags: true
    branch: master
